#!/bin/zsh

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/docs/PROJECT_SNAPSHOT.md"
TMP_FILE="$(mktemp)"

cd "$ROOT_DIR"

timestamp="$(date '+%Y-%m-%d %H:%M:%S %Z')"

append_heading() {
    local heading="$1"
    print -- "" >> "$TMP_FILE"
    print -- "$heading" >> "$TMP_FILE"
    print -- "" >> "$TMP_FILE"
}

append_paths() {
    local target_path="$1"
    if [ -d "$target_path" ]; then
        find "$target_path" -type f ! -name '.DS_Store' | sort | sed 's#^\./##; s#^#- `#; s#$#`#' >> "$TMP_FILE"
    elif [ -f "$target_path" ]; then
        print -- "- \`$target_path\`" >> "$TMP_FILE"
    fi
}

append_rg_list() {
    local pattern="$1"
    shift
    if rg -n "$pattern" "$@" > /dev/null 2>&1; then
        rg -n "$pattern" "$@" | sed 's#^#- `#; s#$#`#' >> "$TMP_FILE"
    else
        print -- "- None" >> "$TMP_FILE"
    fi
}

append_file_block() {
    local label="$1"
    local file="$2"
    print -- "### $label" >> "$TMP_FILE"
    print -- "" >> "$TMP_FILE"
    if [ -f "$file" ]; then
        print -- '```toml' >> "$TMP_FILE"
        sed -n '1,260p' "$file" >> "$TMP_FILE"
        print -- '```' >> "$TMP_FILE"
    else
        print -- "- Missing: \`$file\`" >> "$TMP_FILE"
    fi
    print -- "" >> "$TMP_FILE"
}

{
    print -- "# Project Snapshot"
    print -- ""
    print -- "_Generated by \`scripts/update_project_inventory.sh\` on $timestamp._"
    print -- ""
    print -- "This file is autogenerated. Refresh it after structural changes to code, resources, or dependencies."

    append_heading "## Root Inventory"
    for file in README.md HANDOFF.md VERIFICATION.md roadmap.md build.gradle.kts settings.gradle.kts gradle.properties local.properties; do
        if [ -f "$file" ]; then
            print -- "- \`$file\`" >> "$TMP_FILE"
        fi
    done

    append_heading "## Source File Inventory"
    append_paths "app/src/main/java"
    append_paths "app/src/main/res"
    append_paths "app/src/main/assets"
    append_paths "app/src/test/java"
    append_paths "app/src/androidTest/java"

    append_heading "## Kotlin Type Inventory"
    append_rg_list "^(internal |private |public )?(data class|enum class|class|interface|object) " app/src/main/java app/src/test/java app/src/androidTest/java

    append_heading "## Function And Composable Inventory"
    append_rg_list "^(internal |private |public )?(suspend )?fun |^@Composable" app/src/main/java app/src/test/java app/src/androidTest/java

    append_heading "## Android Resource Inventory"
    append_paths "app/src/main/res"

    append_heading "## Asset Inventory"
    append_paths "app/src/main/assets"

    append_heading "## Manifest Permissions"
    append_rg_list "<uses-permission" app/src/main/AndroidManifest.xml

    append_heading "## Gradle Catalog Snapshot"
    append_file_block "gradle/libs.versions.toml" "gradle/libs.versions.toml"
    append_file_block "app/build.gradle.kts" "app/build.gradle.kts"

    append_heading "## Build Output Inventory"
    if [ -d "app/build/outputs" ]; then
        find app/build/outputs -maxdepth 4 -type f | sort | sed 's#^#- `#; s#$#`#' >> "$TMP_FILE"
    else
        print -- "- No build outputs found." >> "$TMP_FILE"
    fi

    append_heading "## Notes"
    print -- "- Generated files under \`app/build/\` and \`build/\` are included only as artifacts, not as source." >> "$TMP_FILE"
    print -- "- The manual navigation guide remains \`docs/PROJECT_INDEX.md\`." >> "$TMP_FILE"
    print -- "- Run \`./scripts/update_project_inventory.sh\` after adding files, dependencies, or core workflows." >> "$TMP_FILE"
} > "$TMP_FILE"

mv "$TMP_FILE" "$OUTPUT_FILE"
print -- "Updated $OUTPUT_FILE"
